# Generated by Django 5.2.1 on 2025-05-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=200)),
                ('descricao_categoria', models.TextField(blank=True, null=True)),
                ('id_categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='quiz.categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.TextField()),
                ('url_imagem', models.URLField(blank=True, max_length=500, null=True)),
                ('referencia_bibliografica', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel_dificuldade', models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], default='Fácil', max_length=50)),
                ('explicacao_resposta', models.TextField(blank=True, help_text='Explicação geral da resposta correta.', null=True)),
                ('categorias', models.ManyToManyField(related_name='perguntas', to='quiz.categoria')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcao', models.CharField(max_length=500)),
                ('eh_correta', models.BooleanField(default=False)),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, help_text='Usado para ordenar as opções, se necessário.')),
                ('feedback_opcao', models.TextField(blank=True, help_text='Feedback específico para esta opção.', null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='quiz.pergunta')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': 'Opções de Resposta',
                'ordering': ['pergunta', 'ordem_exibicao'],
            },
        ),
    ]
