# Generated by Django 5.2.1 on 2025-05-27 13:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=150, verbose_name='Nome da Categoria')),
                ('descricao_categoria', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('id_categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='quiz.categoria', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome_categoria'],
                'unique_together': {('nome_categoria', 'id_categoria_pai')},
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.TextField(verbose_name='Texto da Pergunta')),
                ('url_imagem', models.URLField(blank=True, max_length=512, null=True, verbose_name='URL da Imagem')),
                ('referencia_bibliografica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência Bibliográfica')),
                ('nivel_dificuldade', models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], default='Médio', max_length=50, verbose_name='Nível de Dificuldade')),
                ('explicacao_resposta', models.TextField(blank=True, help_text='Explicação geral da resposta correta.', null=True, verbose_name='Explicação da Resposta')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categorias', models.ManyToManyField(related_name='perguntas_associadas', to='quiz.categoria', verbose_name='Categorias')),
                ('id_usuario_criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criador da Pergunta')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcao', models.TextField(verbose_name='Texto da Opção')),
                ('eh_correta', models.BooleanField(default=False, verbose_name='É Correta?')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, help_text='Usado para ordenar as opções, se necessário.', verbose_name='Ordem de Exibição')),
                ('feedback_opcao', models.TextField(blank=True, help_text='Feedback específico para esta opção.', null=True, verbose_name='Feedback da Opção')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='quiz.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': 'Opções de Resposta',
                'ordering': ['pergunta', 'ordem_exibicao', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SessoesQuizUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('tempo_total_segundos', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo Total (s)')),
                ('pontuacao_final', models.IntegerField(default=0, verbose_name='Pontuação Final')),
                ('total_perguntas_sessao', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Perguntas na Sessão')),
                ('total_acertos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Acertos')),
                ('total_erros', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Erros')),
                ('modo_quiz', models.CharField(choices=[('Por Categoria', 'Por Categoria'), ('Rápido', 'Rápido')], max_length=50, verbose_name='Modo do Quiz')),
                ('status_sessao', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Completa', 'Completa'), ('Abandonada', 'Abandonada')], default='Em Andamento', max_length=50, verbose_name='Status da Sessão')),
                ('categorias_selecionadas', models.ManyToManyField(blank=True, related_name='sessoes_onde_foi_selecionada', to='quiz.categoria', verbose_name='Categorias Selecionadas (Modo Categoria)')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Quiz do Usuário',
                'verbose_name_plural': 'Sessões de Quiz dos Usuários',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticasDiariasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_estatistica', models.DateField(verbose_name='Data da Estatística')),
                ('perguntas_respondidas_dia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Perguntas Respondidas')),
                ('acertos_dia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Acertos no Dia')),
                ('pontos_dia', models.IntegerField(default=0, verbose_name='Pontos no Dia')),
                ('sequencia_dias_quiz', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sequência de Dias de Quiz')),
                ('tempo_estudo_segundos_dia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo de Estudo no Dia (s)')),
                ('data_atualizacao_estatistica', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_diarias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estatística Diária do Usuário',
                'verbose_name_plural': 'Estatísticas Diárias dos Usuários',
                'ordering': ['id_usuario', '-data_estatistica'],
                'unique_together': {('id_usuario', 'data_estatistica')},
            },
        ),
        migrations.CreateModel(
            name='QuestaoFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_favoritada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inclusão nos Favoritos')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritada_por', to='quiz.pergunta', verbose_name='Pergunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_favoritas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Questão Favorita',
                'verbose_name_plural': 'Questões Favoritas',
                'ordering': ['-data_favoritada'],
                'unique_together': {('usuario', 'pergunta')},
            },
        ),
        migrations.CreateModel(
            name='RespostasUsuarioPorSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foi_correta', models.BooleanField(blank=True, null=True, verbose_name='Foi Correta?')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('id_opcao_resposta_selecionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecionada_em_respostas', to='quiz.opcaoresposta', verbose_name='Opção Selecionada')),
                ('id_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_nesta_sessao', to='quiz.pergunta', verbose_name='Pergunta')),
                ('id_sessao_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_dadas', to='quiz.sessoesquizusuario', verbose_name='Sessão do Quiz')),
            ],
            options={
                'verbose_name': 'Resposta do Usuário por Sessão',
                'verbose_name_plural': 'Respostas dos Usuários por Sessão',
                'ordering': ['id_sessao_quiz', 'data_resposta'],
                'unique_together': {('id_sessao_quiz', 'id_pergunta')},
            },
        ),
    ]
