# Generated by Django 5.2.1 on 2025-05-16 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome_categoria'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='opcaoresposta',
            options={'ordering': ['pergunta', 'ordem_exibicao', 'pk'], 'verbose_name': 'Opção de Resposta', 'verbose_name_plural': 'Opções de Resposta'},
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcaoresposta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opcaoresposta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pergunta',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pergunta',
            name='id_usuario_criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criador da Pergunta'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='texto_opcao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='categorias',
            field=models.ManyToManyField(related_name='perguntas_associadas', to='quiz.categoria'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='nivel_dificuldade',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], default='Médio', max_length=50),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='referencia_bibliografica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='url_imagem',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nome_categoria', 'id_categoria_pai')},
        ),
        migrations.CreateModel(
            name='SessoesQuizUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('tempo_total_segundos', models.IntegerField(blank=True, null=True, verbose_name='Tempo Total (s)')),
                ('pontuacao_final', models.IntegerField(default=0, verbose_name='Pontuação Final')),
                ('total_perguntas_sessao', models.IntegerField(default=0, verbose_name='Total de Perguntas na Sessão')),
                ('total_acertos', models.IntegerField(default=0, verbose_name='Total de Acertos')),
                ('total_erros', models.IntegerField(default=0, verbose_name='Total de Erros')),
                ('modo_quiz', models.CharField(choices=[('Por Categoria', 'Por Categoria'), ('Rápido', 'Rápido')], max_length=50, verbose_name='Modo do Quiz')),
                ('status_sessao', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Completa', 'Completa'), ('Abandonada', 'Abandonada')], default='Em Andamento', max_length=50, verbose_name='Status da Sessão')),
                ('categorias_selecionadas', models.ManyToManyField(blank=True, related_name='sessoes_onde_foi_selecionada', to='quiz.categoria', verbose_name='Categorias Selecionadas')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Quiz do Usuário',
                'verbose_name_plural': 'Sessões de Quiz dos Usuários',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticasDiariasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_estatistica', models.DateField(verbose_name='Data da Estatística')),
                ('perguntas_respondidas_dia', models.IntegerField(default=0, verbose_name='Perguntas Respondidas no Dia')),
                ('acertos_dia', models.IntegerField(default=0, verbose_name='Acertos no Dia')),
                ('pontos_dia', models.IntegerField(default=0, verbose_name='Pontos no Dia')),
                ('sequencia_dias_quiz', models.IntegerField(default=0, verbose_name='Sequência de Dias de Quiz')),
                ('tempo_estudo_segundos_dia', models.IntegerField(default=0, verbose_name='Tempo de Estudo no Dia (s)')),
                ('data_atualizacao_estatistica', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_diarias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estatística Diária do Usuário',
                'verbose_name_plural': 'Estatísticas Diárias dos Usuários',
                'ordering': ['id_usuario', '-data_estatistica'],
                'unique_together': {('id_usuario', 'data_estatistica')},
            },
        ),
        migrations.CreateModel(
            name='RespostasUsuarioPorSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foi_correta', models.BooleanField(blank=True, null=True, verbose_name='Foi Correta?')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('id_opcao_resposta_selecionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecionada_em_respostas', to='quiz.opcaoresposta', verbose_name='Opção Selecionada')),
                ('id_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_nesta_sessao', to='quiz.pergunta', verbose_name='Pergunta')),
                ('id_sessao_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_dadas', to='quiz.sessoesquizusuario', verbose_name='Sessão do Quiz')),
            ],
            options={
                'verbose_name': 'Resposta do Usuário por Sessão',
                'verbose_name_plural': 'Respostas dos Usuários por Sessão',
                'ordering': ['data_resposta'],
                'unique_together': {('id_sessao_quiz', 'id_pergunta')},
            },
        ),
    ]
