# Generated by Django 5.2.1 on 2025-05-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessoesquizusuario',
            name='dificuldades_selecionadas_json',
            field=models.JSONField(blank=True, help_text="Lista de strings com os níveis de dificuldade, ex: ['Fácil', 'Médio'] ou ['all']", null=True, verbose_name='Níveis de Dificuldade Selecionados (JSON)'),
        ),
        migrations.AddField(
            model_name='sessoesquizusuario',
            name='num_questoes_solicitadas',
            field=models.PositiveIntegerField(blank=True, help_text='Número de questões que o usuário pediu (para modo personalizado ou rápido)', null=True, verbose_name='Número de Questões Solicitadas'),
        ),
    ]
