# Generated by Django 5.2.1 on 2025-06-03 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_sessoesquizusuario_dificuldades_selecionadas_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesGeraisQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_perguntas_quiz_rapido', models.PositiveIntegerField(default=10, help_text="Quantidade padrão de perguntas para o modo 'Quiz Rápido', caso o usuário não especifique.", verbose_name='Nº de Perguntas Padrão (Quiz Rápido)')),
                ('pontuacao_por_acerto', models.IntegerField(default=15, help_text='Número de pontos concedidos por cada resposta correta.', verbose_name='Pontos por Acerto')),
                ('penalidade_por_erro', models.IntegerField(default=5, help_text='Número de pontos deduzidos por cada resposta incorreta (use 0 se não houver penalidade).', verbose_name='Penalidade por Erro')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
            ],
            options={
                'verbose_name': 'Configuração Geral do Quiz',
                'verbose_name_plural': 'Configurações Gerais do Quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizDefinicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_quiz', models.CharField(max_length=200, unique=True, verbose_name='Nome do Quiz Definido')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Quiz')),
                ('ativo', models.BooleanField(default=True, help_text='Se este quiz pode ser selecionado pelos usuários.', verbose_name='Quiz Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Definição de Quiz',
                'verbose_name_plural': 'Definições de Quizzes',
                'ordering': ['nome_quiz'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome_categoria'], 'verbose_name': 'Categoria de Pergunta', 'verbose_name_plural': 'Categorias de Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Pergunta do Quiz', 'verbose_name_plural': 'Perguntas do Quiz'},
        ),
        migrations.AlterModelOptions(
            name='questaofavorita',
            options={'ordering': ['-data_favoritada'], 'verbose_name': 'Questão Favorita do Usuário', 'verbose_name_plural': 'Questões Favoritas dos Usuários'},
        ),
        migrations.AddField(
            model_name='sessoesquizusuario',
            name='ids_perguntas_json',
            field=models.JSONField(blank=True, help_text='Lista dos IDs das perguntas que compõem esta sessão, na ordem em que foram apresentadas.', null=True, verbose_name='IDs Ordenados das Perguntas da Sessão'),
        ),
        migrations.AddField(
            model_name='sessoesquizusuario',
            name='indice_ultima_pergunta_vista',
            field=models.PositiveIntegerField(blank=True, help_text="Índice (base 0) na lista 'IDs Ordenados das Perguntas da Sessão' que o usuário visualizou por último.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Índice da Última Pergunta Vista'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria_pai',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco se esta for uma categoria principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='quiz.categoria', verbose_name='Categoria Pai'),
        ),
        migrations.AlterField(
            model_name='estatisticasdiariasusuario',
            name='pontos_dia',
            field=models.IntegerField(default=0, verbose_name='Pontos Ganhos no Dia'),
        ),
        migrations.AlterField(
            model_name='estatisticasdiariasusuario',
            name='sequencia_dias_quiz',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sequência de Dias Consecutivos de Quiz'),
        ),
        migrations.AlterField(
            model_name='estatisticasdiariasusuario',
            name='tempo_estudo_segundos_dia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo de Estudo no Dia (segundos)'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='eh_correta',
            field=models.BooleanField(default=False, help_text='Marque se esta é a opção correta para a pergunta.', verbose_name='É Correta?'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='feedback_opcao',
            field=models.TextField(blank=True, help_text='Feedback específico para esta opção, exibido após o usuário responder.', null=True, verbose_name='Feedback da Opção (Opcional)'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='ordem_exibicao',
            field=models.PositiveIntegerField(default=0, help_text='Usado para ordenar as opções na exibição, se necessário (0, 1, 2...).', verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='quiz.pergunta', verbose_name='Pergunta Associada'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Perguntas inativas não aparecerão nos quizzes.', verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='categorias',
            field=models.ManyToManyField(help_text='Selecione uma ou mais categorias para esta pergunta.', related_name='perguntas_associadas', to='quiz.categoria', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='explicacao_resposta',
            field=models.TextField(blank=True, help_text='Explicação detalhada da resposta correta ou do tópico da pergunta.', null=True, verbose_name='Explicação da Resposta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='url_imagem',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL da Imagem (Opcional)'),
        ),
        migrations.AlterField(
            model_name='questaofavorita',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritada_por_usuarios', to='quiz.pergunta', verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='respostasusuarioporsessao',
            name='foi_correta',
            field=models.BooleanField(blank=True, help_text='True se correta, False se incorreta, Nulo se pulada/não respondida.', null=True, verbose_name='Foi Correta?'),
        ),
        migrations.AlterField(
            model_name='respostasusuarioporsessao',
            name='id_opcao_resposta_selecionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vezes_selecionada_em_respostas', to='quiz.opcaoresposta', verbose_name='Opção Selecionada'),
        ),
        migrations.AlterField(
            model_name='respostasusuarioporsessao',
            name='id_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_dadas_em_sessoes', to='quiz.pergunta', verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='sessoesquizusuario',
            name='categorias_selecionadas',
            field=models.ManyToManyField(blank=True, related_name='sessoes_filtradas_por_categoria', to='quiz.categoria', verbose_name='Categorias Selecionadas (Modo Categoria)'),
        ),
        migrations.AlterField(
            model_name='sessoesquizusuario',
            name='dificuldades_selecionadas_json',
            field=models.JSONField(blank=True, help_text="Lista de níveis de dificuldade selecionados, ex: ['Fácil', 'Médio'] ou ['all']", null=True, verbose_name='Níveis de Dificuldade Selecionados (JSON)'),
        ),
        migrations.AlterField(
            model_name='sessoesquizusuario',
            name='modo_quiz',
            field=models.CharField(choices=[('Por Categoria', 'Por Categoria'), ('Rápido', 'Rápido'), ('Definido', 'Pré-Definido')], max_length=50, verbose_name='Modo do Quiz'),
        ),
        migrations.AddField(
            model_name='sessoesquizusuario',
            name='id_quiz_definicao',
            field=models.ForeignKey(blank=True, help_text='Se esta sessão foi baseada em um quiz pré-definido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_realizadas', to='quiz.quizdefinicao', verbose_name='Quiz Pré-definido (se aplicável)'),
        ),
        migrations.CreateModel(
            name='QuizDefinicaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(help_text='Define a posição da pergunta dentro deste quiz (começando em 0 ou 1).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ordem no Quiz')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pergunta', verbose_name='Pergunta')),
                ('quiz_definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizdefinicao', verbose_name='Definição do Quiz')),
            ],
            options={
                'verbose_name': 'Pergunta em Definição de Quiz',
                'verbose_name_plural': 'Perguntas em Definições de Quizzes',
                'ordering': ['quiz_definicao', 'ordem'],
                'unique_together': {('quiz_definicao', 'ordem'), ('quiz_definicao', 'pergunta')},
            },
        ),
        migrations.AddField(
            model_name='quizdefinicao',
            name='perguntas',
            field=models.ManyToManyField(related_name='definicoes_quiz_associadas', through='quiz.QuizDefinicaoPergunta', to='quiz.pergunta', verbose_name='Perguntas do Quiz'),
        ),
    ]
