# Generated by Django 5.2.1 on 2025-05-17 02:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_categoria_options_alter_opcaoresposta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respostasusuarioporsessao',
            options={'ordering': ['id_sessao_quiz', 'data_resposta'], 'verbose_name': 'Resposta do Usuário por Sessão', 'verbose_name_plural': 'Respostas dos Usuários por Sessão'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao_categoria',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='quiz.categoria', verbose_name='Categoria Pai'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(max_length=150, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='estatisticasdiariasusuario',
            name='acertos_dia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Acertos no Dia'),
        ),
        migrations.AlterField(
            model_name='estatisticasdiariasusuario',
            name='perguntas_respondidas_dia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Perguntas Respondidas'),
        ),
        migrations.AlterField(
            model_name='estatisticasdiariasusuario',
            name='sequencia_dias_quiz',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sequência de Dias de Quiz'),
        ),
        migrations.AlterField(
            model_name='estatisticasdiariasusuario',
            name='tempo_estudo_segundos_dia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo de Estudo no Dia (s)'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='eh_correta',
            field=models.BooleanField(default=False, verbose_name='É Correta?'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='feedback_opcao',
            field=models.TextField(blank=True, help_text='Feedback específico para esta opção.', null=True, verbose_name='Feedback da Opção'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='ordem_exibicao',
            field=models.PositiveIntegerField(default=0, help_text='Usado para ordenar as opções, se necessário.', verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='quiz.pergunta', verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='texto_opcao',
            field=models.TextField(verbose_name='Texto da Opção'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='categorias',
            field=models.ManyToManyField(related_name='perguntas_associadas', to='quiz.categoria', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='explicacao_resposta',
            field=models.TextField(blank=True, help_text='Explicação geral da resposta correta.', null=True, verbose_name='Explicação da Resposta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='nivel_dificuldade',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], default='Médio', max_length=50, verbose_name='Nível de Dificuldade'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='referencia_bibliografica',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência Bibliográfica'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto_pergunta',
            field=models.TextField(verbose_name='Texto da Pergunta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='url_imagem',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='sessoesquizusuario',
            name='categorias_selecionadas',
            field=models.ManyToManyField(blank=True, related_name='sessoes_onde_foi_selecionada', to='quiz.categoria', verbose_name='Categorias Selecionadas (Modo Categoria)'),
        ),
        migrations.AlterField(
            model_name='sessoesquizusuario',
            name='tempo_total_segundos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo Total (s)'),
        ),
        migrations.AlterField(
            model_name='sessoesquizusuario',
            name='total_acertos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Acertos'),
        ),
        migrations.AlterField(
            model_name='sessoesquizusuario',
            name='total_erros',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Erros'),
        ),
        migrations.AlterField(
            model_name='sessoesquizusuario',
            name='total_perguntas_sessao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Perguntas na Sessão'),
        ),
        migrations.CreateModel(
            name='QuestaoFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_favoritada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inclusão nos Favoritos')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritada_por', to='quiz.pergunta', verbose_name='Pergunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_favoritas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Questão Favorita',
                'verbose_name_plural': 'Questões Favoritas',
                'ordering': ['-data_favoritada'],
                'unique_together': {('usuario', 'pergunta')},
            },
        ),
    ]
