# Generated by Django 5.2.1 on 2025-09-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_categoriahierarquia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoriahierarquia',
            name='unique_categoriahierarquia_ancestor_descendant',
        ),
        migrations.RenameIndex(
            model_name='categoriahierarquia',
            new_name='cat_hier_anc_desc_idx',
            old_name='categoriahierarquia_ancestor_descendant_idx',
        ),
        migrations.RenameIndex(
            model_name='categoriahierarquia',
            new_name='cat_hier_desc_anc_idx',
            old_name='categoriahierarquia_descendant_ancestor_idx',
        ),
        migrations.AddConstraint(
            model_name='categoriahierarquia',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='uq_cat_hier_anc_desc'),
        ),
    ]
