# Generated by Django 5.2.1 on 2025-09-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_categoriahierarquia_unique_categoriahierarquia_ancestor_descendant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codigo_importacao',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Identificador externo usado durante processos de importação.',
                max_length=64,
                null=True,
                unique=True,
                verbose_name='Código de Importação',
            ),
        ),
        migrations.AddField(
            model_name='opcaoresposta',
            name='codigo_importacao',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Identificador externo usado durante processos de importação.',
                max_length=64,
                null=True,
                unique=True,
                verbose_name='Código de Importação',
            ),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='codigo_importacao',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Identificador externo usado durante processos de importação.',
                max_length=64,
                null=True,
                unique=True,
                verbose_name='Código de Importação',
            ),
        ),
    ]
