# Generated by Django 5.2.1 on 2025-09-20 00:00

from django.db import migrations


def populate_codigo_importacao(apps, schema_editor):
    Categoria = apps.get_model('quiz', 'Categoria')
    Pergunta = apps.get_model('quiz', 'Pergunta')
    OpcaoResposta = apps.get_model('quiz', 'OpcaoResposta')

    for model in (Categoria, Pergunta, OpcaoResposta):
        for obj in model.objects.all().iterator():
            if not obj.codigo_importacao:
                obj.codigo_importacao = str(obj.pk)
                obj.save(update_fields=['codigo_importacao'])


def unpopulate_codigo_importacao(apps, schema_editor):
    Categoria = apps.get_model('quiz', 'Categoria')
    Pergunta = apps.get_model('quiz', 'Pergunta')
    OpcaoResposta = apps.get_model('quiz', 'OpcaoResposta')

    for model in (Categoria, Pergunta, OpcaoResposta):
        for obj in model.objects.all().iterator():
            if obj.codigo_importacao == str(obj.pk):
                obj.codigo_importacao = None
                obj.save(update_fields=['codigo_importacao'])


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_add_codigo_importacao_fields'),
    ]

    operations = [
        migrations.RunPython(populate_codigo_importacao, reverse_code=unpopulate_codigo_importacao),
    ]
