# Generated by Django 4.2.7 on 2025-09-26 18:00

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quiz",
            "0011_remove_progressodesafiousuario_quiz_progresso_desafio_usuario_desafio_perfil_uniq_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracoesgeraisquiz",
            name="score_panel_config",
            field=models.JSONField(
                default=quiz.models.default_score_panel_config,
                help_text="Mapa JSON que define a visibilidade e permissões do painel de pontuação para cada modo de quiz (Por Categoria, Rápido e Definido).",
                verbose_name="Configurações do Painel de Pontuação",
            ),
        ),
    ]
