# Generated by Django 4.2.7 on 2025-09-26 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_configuracoesgeraisquiz_score_panel_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respostasusuarioporsessao",
            name="data_resposta",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data da Resposta"
            ),
        ),
    ]
