# Generated by Django 5.2.1 on 2025-09-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0013_alter_respostasusuarioporsessao_data_resposta"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMessageBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Usado como chave estável para a mensagem. Não use espaços nem caracteres especiais.",
                        unique=True,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=150, verbose_name="Título"),
                ),
                ("body", models.TextField(verbose_name="Mensagem principal")),
                (
                    "supporting_text",
                    models.TextField(
                        blank=True,
                        help_text="Opcional: complemento exibido abaixo do corpo principal.",
                        verbose_name="Texto complementar",
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        help_text="Valor passado como detail para renderizações personalizadas.",
                        max_length=255,
                        verbose_name="Detalhe adicional",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("info", "Informação"),
                            ("warning", "Aviso"),
                            ("error", "Erro"),
                        ],
                        default="info",
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone do Google Material Symbols (opcional).",
                        max_length=40,
                        verbose_name="Ícone personalizado",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("toast", "Toast (notificação)"),
                            ("inline", "Inline (painel embutido)"),
                        ],
                        default="toast",
                        max_length=10,
                        verbose_name="Canal padrão",
                    ),
                ),
                (
                    "extra_tags",
                    models.CharField(
                        blank=True,
                        help_text="Separadas por espaço. Use, por exemplo, 'sticky centered inline'.",
                        max_length=200,
                        verbose_name="Tags extras",
                    ),
                ),
                (
                    "auto_dismiss",
                    models.BooleanField(
                        default=True,
                        help_text="Define se o toast deve sumir sozinho após alguns segundos.",
                        verbose_name="Fechar automaticamente",
                    ),
                ),
                (
                    "dismiss_in",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tempo em milissegundos para fechar automaticamente. Deixe em branco para usar o padrão.",
                        null=True,
                        verbose_name="Dispensar em (ms)",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Todos os usuários"),
                            ("auth", "Somente usuários autenticados"),
                            ("anon", "Somente visitantes anônimos"),
                        ],
                        default="all",
                        max_length=8,
                        verbose_name="Audiência",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Mensagens com prioridade mais alta aparecem primeiro.",
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desative para ocultar sem apagar a mensagem.",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Opcional: data/hora a partir da qual a mensagem é exibida.",
                        null=True,
                        verbose_name="Início da vigência",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Opcional: data/hora após a qual a mensagem deixa de ser exibida.",
                        null=True,
                        verbose_name="Fim da vigência",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizada em"),
                ),
            ],
            options={
                "verbose_name": "Mensagem do Sistema",
                "verbose_name_plural": "Mensagens do Sistema",
                "ordering": ["-priority", "-start_at", "title"],
            },
        ),
    ]
