# Generated by Django 5.2.6 on 2025-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_adaptive_study_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessoesquizusuario',
            name='metodo_estudo',
            field=models.CharField(blank=True, default='random', help_text='Identificador do algoritmo utilizado para selecionar as perguntas da sessão.', max_length=100, null=True, verbose_name='Método de Estudo'),
        ),
    ]
