# Generated by Django 5.2.6 on 2025-09-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_sessoesquizusuario_metodo_estudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo_importacao',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador externo usado durante processos de importação. Deixe em branco para gerar automaticamente.', max_length=64, null=True, unique=True, verbose_name='Código de Importação'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='codigo_importacao',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador externo usado durante processos de importação. Deixe em branco para gerar automaticamente.', max_length=64, null=True, unique=True, verbose_name='Código de Importação'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='codigo_importacao',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador externo usado durante processos de importação. Deixe em branco para gerar automaticamente.', max_length=64, null=True, unique=True, verbose_name='Código de Importação'),
        ),
    ]
