# Generated by Django 5.2.7 on 2025-10-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0018_alter_categoria_codigo_importacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeHubSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        default="Hub de desafios MedQuiz",
                        help_text="Texto curto acima do título do Challenge Hub.",
                        max_length=120,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Escolha seu próximo desafio",
                        help_text="Título principal do Challenge Hub.",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle_template",
                    models.CharField(
                        default="Combine modos inteligentes de estudo e aproveite as {total_questions} questões disponíveis.",
                        help_text="Use {total_questions} para inserir automaticamente o contador principal.",
                        max_length=320,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurações do Challenge Hub",
            },
        ),
        migrations.CreateModel(
            name="HomePageSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "hero_authenticated_eyebrow",
                    models.CharField(
                        default="Hub de estudos MedQuiz",
                        help_text="Texto curto acima do título para usuários autenticados.",
                        max_length=120,
                    ),
                ),
                (
                    "hero_authenticated_title",
                    models.CharField(
                        default="Bem-vindo de volta, {first_name}.",
                        help_text="Use {first_name} para inserir automaticamente o primeiro nome do usuário logado.",
                        max_length=200,
                    ),
                ),
                (
                    "hero_authenticated_subtitle",
                    models.CharField(
                        default="Veja seu progresso em uma linha, foque no que rende agora e retome a prática com atalhos pensados para o seu ritmo.",
                        help_text="Subtítulo exibido quando o usuário está autenticado.",
                        max_length=300,
                    ),
                ),
                (
                    "hero_anonymous_eyebrow",
                    models.CharField(
                        default="Hub de estudos MedQuiz",
                        help_text="Texto curto acima do título para visitantes.",
                        max_length=120,
                    ),
                ),
                (
                    "hero_anonymous_title",
                    models.CharField(
                        default="Domine medicina com treinos guiados e métricas em tempo real.",
                        help_text="Título da hero section para visitantes.",
                        max_length=200,
                    ),
                ),
                (
                    "hero_anonymous_subtitle",
                    models.CharField(
                        default="Estude em blocos inteligentes, acompanhe evolução e mantenha constância com feedback imediato.",
                        help_text="Subtítulo exibido para visitantes.",
                        max_length=320,
                    ),
                ),
                (
                    "quick_section_title",
                    models.CharField(
                        default="Continue de onde parou",
                        help_text="Título da seção de atalhos rápidos para usuários autenticados.",
                        max_length=200,
                    ),
                ),
                (
                    "quick_section_subtitle",
                    models.CharField(
                        default="Entre direto nos modos que mantêm sua evolução em alta.",
                        help_text="Descrição curta da seção de atalhos.",
                        max_length=250,
                    ),
                ),
                (
                    "intro_section_title",
                    models.CharField(
                        default="Por que começar pelo MedQuiz?",
                        help_text="Título da seção introdutória para visitantes.",
                        max_length=200,
                    ),
                ),
                (
                    "intro_section_subtitle",
                    models.CharField(
                        default="Um ecossistema completo para criar constância nos estudos.",
                        help_text="Descrição curta da seção introdutória para visitantes.",
                        max_length=250,
                    ),
                ),
                (
                    "intro_highlight_eyebrow",
                    models.CharField(
                        default="Resultados comprovados",
                        help_text="Eyebrow card da coluna de destaques na home pública.",
                        max_length=120,
                    ),
                ),
                (
                    "intro_highlight_title",
                    models.CharField(
                        default="Métricas e conteúdos sempre atualizados",
                        help_text="Título do card de destaques na home pública.",
                        max_length=200,
                    ),
                ),
                (
                    "intro_steps_eyebrow",
                    models.CharField(
                        default="Comece agora",
                        help_text="Eyebrow do card de passos iniciais para visitantes.",
                        max_length=120,
                    ),
                ),
                (
                    "intro_steps_title",
                    models.CharField(
                        default="Três passos para entrar no ritmo",
                        help_text="Título do card de passos para visitantes.",
                        max_length=200,
                    ),
                ),
                (
                    "intro_primary_cta_label",
                    models.CharField(
                        default="Criar conta",
                        help_text="Rótulo do botão principal do card de passos.",
                        max_length=120,
                    ),
                ),
                (
                    "intro_primary_cta_url",
                    models.CharField(
                        default="/register/",
                        help_text="URL relativa ou absoluta para o CTA principal do card de passos.",
                        max_length=255,
                    ),
                ),
                (
                    "intro_secondary_cta_label",
                    models.CharField(
                        default="Experimentar um quiz",
                        help_text="Rótulo do botão secundário do card de passos.",
                        max_length=120,
                    ),
                ),
                (
                    "intro_secondary_cta_url",
                    models.CharField(
                        default="/questions/",
                        help_text="URL relativa ou absoluta para o CTA secundário do card de passos.",
                        max_length=255,
                    ),
                ),
                (
                    "collections_section_title",
                    models.CharField(
                        default="Coleções em destaque",
                        help_text="Título da seção de coleções.",
                        max_length=200,
                    ),
                ),
                (
                    "collections_section_subtitle",
                    models.CharField(
                        default="Seleções diretas para revisar rapidamente os temas mais cobrados.",
                        help_text="Descrição da seção de coleções.",
                        max_length=250,
                    ),
                ),
                (
                    "methods_section_title",
                    models.CharField(
                        default="Métodos de estudo disponíveis",
                        help_text="Título da seção de métodos de estudo.",
                        max_length=200,
                    ),
                ),
                (
                    "methods_section_subtitle",
                    models.CharField(
                        default="Ajuste a abordagem conforme o objetivo da semana.",
                        help_text="Descrição da seção de métodos.",
                        max_length=250,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurações da Home",
            },
        ),
        migrations.CreateModel(
            name="ChallengeHubResumeCardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Retomar sessão", max_length=150)),
                (
                    "description_template",
                    models.CharField(
                        default="Você tem uma sessão em andamento de <strong>{question_count}</strong> questões.",
                        help_text="Use {question_count} para inserir a contagem dinâmica.",
                        max_length=300,
                    ),
                ),
                ("icon", models.CharField(default="autorenew", max_length=80)),
                (
                    "discard_label",
                    models.CharField(default="Descartar", max_length=120),
                ),
                (
                    "continue_label",
                    models.CharField(default="Continuar", max_length=120),
                ),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_card",
                        to="quiz.challengehubsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do card de retomada",
            },
        ),
        migrations.CreateModel(
            name="ChallengeHubPredefinedSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Listas especiais", max_length=200)),
                (
                    "subtitle",
                    models.CharField(
                        default="Explore quizzes prontos com curadoria da equipe MedQuiz.",
                        max_length=250,
                    ),
                ),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predefined_section",
                        to="quiz.challengehubsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção de coleções do Challenge Hub",
            },
        ),
        migrations.CreateModel(
            name="ChallengeHubHeroStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(max_length=150)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("total_questions", "Total de questões"),
                            ("quick_quiz_default", "Total sugerido para quiz rápido"),
                            ("predefined_total", "Quantidade de coleções prontas"),
                        ],
                        max_length=30,
                    ),
                ),
                ("dom_id", models.CharField(blank=True, max_length=120)),
                ("prefix", models.CharField(blank=True, max_length=40)),
                ("suffix", models.CharField(blank=True, max_length=40)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_stats",
                        to="quiz.challengehubsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrica do Challenge Hub",
                "verbose_name_plural": "Métricas do Challenge Hub",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ChallengeHubHeroAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("customize", "Botão Personalizar"),
                            ("quick_start", "Botão Começar Agora"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("icon", models.CharField(default="play_arrow", max_length=80)),
                (
                    "css_class",
                    models.CharField(
                        default="button button--fancy button--fancy-primary challenge-hub__action-button",
                        max_length=200,
                    ),
                ),
                ("dom_id", models.CharField(max_length=120, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_actions",
                        to="quiz.challengehubsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação do Challenge Hub",
                "verbose_name_plural": "Ações do Challenge Hub",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="ChallengeHubActionCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("smart_drill", "Foco guiado"),
                            ("timed_quiz", "Simulado cronometrado"),
                            ("favorite_review", "Revisão de favoritos"),
                            ("repeat_last", "Repetir último desafio"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=250)),
                ("meta", models.CharField(blank=True, max_length=250)),
                ("icon", models.CharField(default="quiz", max_length=80)),
                ("dom_id", models.CharField(max_length=120, unique=True)),
                ("extra_css_class", models.CharField(blank=True, max_length=150)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_cards",
                        to="quiz.challengehubsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card do Challenge Hub",
                "verbose_name_plural": "Cards do Challenge Hub",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="HomeIntroStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("text", models.CharField(max_length=200)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intro_steps",
                        to="quiz.homepagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passo Inicial",
                "verbose_name_plural": "Passos Iniciais",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="HomeIntroHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("icon", models.CharField(default="quiz", max_length=80)),
                ("label", models.CharField(max_length=150)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("static", "Valor definido manualmente"),
                            ("daily_responded", "Perguntas respondidas no dia"),
                            ("daily_accuracy", "Precisão diária"),
                            ("streak_days", "Dias de sequência ativa"),
                            ("platform_total_questions", "Total de questões do banco"),
                            ("platform_total_categories", "Total de categorias"),
                            ("platform_curated_count", "Curadorias ativas"),
                            ("quick_quiz_default", "Quantidade padrão do quiz rápido"),
                            (
                                "predefined_collections",
                                "Total de coleções pré-definidas",
                            ),
                        ],
                        default="static",
                        max_length=60,
                    ),
                ),
                ("static_value", models.CharField(blank=True, max_length=120)),
                ("dom_id", models.CharField(blank=True, max_length=120)),
                ("prefix", models.CharField(blank=True, max_length=40)),
                ("suffix", models.CharField(blank=True, max_length=40)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intro_highlights",
                        to="quiz.homepagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador Introdutório",
                "verbose_name_plural": "Indicadores Introdutórios",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="HomeHeroStatTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("authenticated", "Usuários autenticados"),
                            ("anonymous", "Visitantes"),
                        ],
                        default="authenticated",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("icon", models.CharField(default="quiz", max_length=80)),
                ("label", models.CharField(max_length=120)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("static", "Valor definido manualmente"),
                            ("daily_responded", "Perguntas respondidas no dia"),
                            ("daily_accuracy", "Precisão diária"),
                            ("streak_days", "Dias de sequência ativa"),
                            ("platform_total_questions", "Total de questões do banco"),
                            ("platform_total_categories", "Total de categorias"),
                            ("platform_curated_count", "Curadorias ativas"),
                            ("quick_quiz_default", "Quantidade padrão do quiz rápido"),
                            (
                                "predefined_collections",
                                "Total de coleções pré-definidas",
                            ),
                        ],
                        default="static",
                        max_length=60,
                    ),
                ),
                ("prefix", models.CharField(blank=True, max_length=40)),
                ("suffix", models.CharField(blank=True, max_length=40)),
                ("static_value", models.CharField(blank=True, max_length=120)),
                (
                    "dom_id",
                    models.CharField(
                        blank=True,
                        help_text="ID opcional aplicado ao valor para integrações JS.",
                        max_length=120,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_stat_templates",
                        to="quiz.homepagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrica da Hero",
                "verbose_name_plural": "Métricas da Hero",
                "ordering": ("audience", "order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="HomeQuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=250)),
                ("icon", models.CharField(default="rocket_launch", max_length=80)),
                ("url", models.CharField(max_length=255)),
                ("extra_css_class", models.CharField(blank=True, max_length=150)),
                ("anchor_id", models.CharField(blank=True, max_length=120)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_links",
                        to="quiz.homepagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atalho Rápido",
                "verbose_name_plural": "Atalhos Rápidos",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="HomeHeroCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("authenticated", "Usuários autenticados"),
                            ("anonymous", "Visitantes"),
                        ],
                        default="authenticated",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("primary", "Principal"), ("secondary", "Secundário")],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "url",
                    models.CharField(
                        help_text="Use URLs relativas (ex: /questions/) ou absolutas.",
                        max_length=255,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone Material Symbols a exibir.",
                        max_length=80,
                    ),
                ),
                (
                    "css_class",
                    models.CharField(
                        default="button button--fancy button--fancy-primary",
                        help_text="Classes CSS completas aplicadas ao botão.",
                        max_length=200,
                    ),
                ),
                (
                    "anchor_id",
                    models.CharField(
                        blank=True,
                        help_text="ID opcional usado para tracking ou integrações front-end.",
                        max_length=120,
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, help_text="Abrir link em nova aba."
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_ctas",
                        to="quiz.homepagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "CTA da Home",
                "verbose_name_plural": "CTAs da Home",
                "ordering": ("audience", "position"),
                "unique_together": {("settings", "audience", "position")},
            },
        ),
    ]
