# Generated by Django 5.2.7 on 2025-10-08 13:47

from django.db import migrations


def create_default_content(apps, schema_editor):
    HomePageSettings = apps.get_model("quiz", "HomePageSettings")
    HomeHeroCTA = apps.get_model("quiz", "HomeHeroCTA")
    HomeHeroStatTemplate = apps.get_model("quiz", "HomeHeroStatTemplate")
    HomeQuickLink = apps.get_model("quiz", "HomeQuickLink")
    HomeIntroHighlight = apps.get_model("quiz", "HomeIntroHighlight")
    HomeIntroStep = apps.get_model("quiz", "HomeIntroStep")

    ChallengeHubSettings = apps.get_model("quiz", "ChallengeHubSettings")
    ChallengeHubHeroAction = apps.get_model("quiz", "ChallengeHubHeroAction")
    ChallengeHubHeroStat = apps.get_model("quiz", "ChallengeHubHeroStat")
    ChallengeHubActionCard = apps.get_model("quiz", "ChallengeHubActionCard")
    ChallengeHubResumeCardSettings = apps.get_model("quiz", "ChallengeHubResumeCardSettings")
    ChallengeHubPredefinedSection = apps.get_model("quiz", "ChallengeHubPredefinedSection")

    home_settings, _ = HomePageSettings.objects.get_or_create(pk=1)

    HomeHeroCTA.objects.update_or_create(
        settings=home_settings,
        audience="authenticated",
        position="primary",
        defaults={
            "label": "Iniciar novo quiz",
            "url": "/questions/",
            "icon": "rocket_launch",
            "css_class": "button button--fancy button--fancy-primary",
            "anchor_id": "go-to-challenges-hub-link",
            "open_in_new_tab": False,
            "is_enabled": True,
        },
    )
    HomeHeroCTA.objects.update_or_create(
        settings=home_settings,
        audience="authenticated",
        position="secondary",
        defaults={
            "label": "Abrir painel completo",
            "url": "/account/",
            "icon": "insights",
            "css_class": "button button--outline",
            "anchor_id": "",
            "open_in_new_tab": False,
            "is_enabled": True,
        },
    )
    HomeHeroCTA.objects.update_or_create(
        settings=home_settings,
        audience="anonymous",
        position="primary",
        defaults={
            "label": "Criar conta gratuita",
            "url": "/register/",
            "icon": "person_add",
            "css_class": "button button--fancy button--fancy-primary",
            "anchor_id": "",
            "open_in_new_tab": False,
            "is_enabled": True,
        },
    )
    HomeHeroCTA.objects.update_or_create(
        settings=home_settings,
        audience="anonymous",
        position="secondary",
        defaults={
            "label": "Explorar banco de questões",
            "url": "/questions/",
            "icon": "quiz",
            "css_class": "button button--fancy button--fancy-secondary",
            "anchor_id": "",
            "open_in_new_tab": False,
            "is_enabled": True,
        },
    )

    HomeHeroStatTemplate.objects.update_or_create(
        settings=home_settings,
        audience="authenticated",
        order=1,
        defaults={
            "icon": "checklist",
            "label": "Respondidas hoje",
            "data_source": "daily_responded",
            "dom_id": "",
            "is_enabled": True,
        },
    )
    HomeHeroStatTemplate.objects.update_or_create(
        settings=home_settings,
        audience="authenticated",
        order=2,
        defaults={
            "icon": "target",
            "label": "Precisão diária",
            "data_source": "daily_accuracy",
            "dom_id": "",
            "is_enabled": True,
        },
    )
    HomeHeroStatTemplate.objects.update_or_create(
        settings=home_settings,
        audience="authenticated",
        order=3,
        defaults={
            "icon": "local_fire_department",
            "label": "Sequência ativa",
            "data_source": "streak_days",
            "suffix": " dias",
            "dom_id": "",
            "is_enabled": True,
        },
    )
    HomeHeroStatTemplate.objects.update_or_create(
        settings=home_settings,
        audience="anonymous",
        order=1,
        defaults={
            "icon": "quiz",
            "label": "Questões disponíveis",
            "data_source": "platform_total_questions",
            "dom_id": "challenge-stat-total",
            "is_enabled": True,
        },
    )
    HomeHeroStatTemplate.objects.update_or_create(
        settings=home_settings,
        audience="anonymous",
        order=2,
        defaults={
            "icon": "category",
            "label": "Categorias de estudo",
            "data_source": "platform_total_categories",
            "dom_id": "",
            "is_enabled": True,
        },
    )
    HomeHeroStatTemplate.objects.update_or_create(
        settings=home_settings,
        audience="anonymous",
        order=3,
        defaults={
            "icon": "hub",
            "label": "Curadorias ativas",
            "data_source": "platform_curated_count",
            "dom_id": "",
            "is_enabled": True,
        },
    )

    HomeQuickLink.objects.update_or_create(
        settings=home_settings,
        order=1,
        defaults={
            "title": "Iniciar desafio rápido",
            "description": "Abra o hub de desafios configurado para você.",
            "icon": "rocket_launch",
            "url": "/questions/",
            "anchor_id": "quick-link-start",
            "extra_css_class": "",
            "open_in_new_tab": False,
            "is_enabled": True,
        },
    )
    HomeQuickLink.objects.update_or_create(
        settings=home_settings,
        order=2,
        defaults={
            "title": "Revisar favoritos",
            "description": "Volte às questões salvas e organize seus estudos.",
            "icon": "star",
            "url": "/account/#painel-favoritos",
            "anchor_id": "",
            "extra_css_class": "",
            "open_in_new_tab": False,
            "is_enabled": True,
        },
    )
    HomeQuickLink.objects.update_or_create(
        settings=home_settings,
        order=3,
        defaults={
            "title": "Explorar coleções prontas",
            "description": "Seleções temáticas com tempo estimado e foco claro.",
            "icon": "playlist_add_check",
            "url": "/questions/#hub-predefined-section",
            "anchor_id": "",
            "extra_css_class": "",
            "open_in_new_tab": False,
            "is_enabled": True,
        },
    )

    HomeIntroHighlight.objects.update_or_create(
        settings=home_settings,
        order=1,
        defaults={
            "icon": "quiz",
            "label": "Questões disponíveis",
            "data_source": "platform_total_questions",
            "dom_id": "challenge-stat-total",
            "is_enabled": True,
        },
    )
    HomeIntroHighlight.objects.update_or_create(
        settings=home_settings,
        order=2,
        defaults={
            "icon": "category",
            "label": "Categorias",
            "data_source": "platform_total_categories",
            "is_enabled": True,
        },
    )
    HomeIntroHighlight.objects.update_or_create(
        settings=home_settings,
        order=3,
        defaults={
            "icon": "play_arrow",
            "label": "Padrão do quiz rápido",
            "data_source": "quick_quiz_default",
            "is_enabled": True,
        },
    )

    HomeIntroStep.objects.update_or_create(
        settings=home_settings,
        order=1,
        defaults={"text": "Crie uma conta gratuita"},
    )
    HomeIntroStep.objects.update_or_create(
        settings=home_settings,
        order=2,
        defaults={"text": "Escolha um modo ou coleção"},
    )
    HomeIntroStep.objects.update_or_create(
        settings=home_settings,
        order=3,
        defaults={"text": "Acompanhe desempenho em tempo real"},
    )

    challenge_settings, _ = ChallengeHubSettings.objects.get_or_create(pk=1)

    ChallengeHubHeroAction.objects.update_or_create(
        settings=challenge_settings,
        key="customize",
        defaults={
            "label": "Personalizar",
            "icon": "tune",
            "css_class": "button button--fancy button--fancy-secondary challenge-hub__action-button",
            "dom_id": "hub-customize-quiz-btn",
            "is_enabled": True,
        },
    )
    ChallengeHubHeroAction.objects.update_or_create(
        settings=challenge_settings,
        key="quick_start",
        defaults={
            "label": "Começar agora",
            "icon": "play_arrow",
            "css_class": "button button--fancy button--fancy-primary challenge-hub__action-button",
            "dom_id": "hub-quick-quiz-btn",
            "is_enabled": True,
        },
    )

    ChallengeHubHeroStat.objects.update_or_create(
        settings=challenge_settings,
        order=1,
        defaults={
            "label": "Questões no banco",
            "data_source": "total_questions",
            "dom_id": "challenge-stat-total",
            "is_enabled": True,
        },
    )
    ChallengeHubHeroStat.objects.update_or_create(
        settings=challenge_settings,
        order=2,
        defaults={
            "label": "Quiz rápido sugerido",
            "data_source": "quick_quiz_default",
            "dom_id": "hub-quick-quiz-count",
            "is_enabled": True,
        },
    )

    ChallengeHubActionCard.objects.update_or_create(
        settings=challenge_settings,
        key="smart_drill",
        defaults={
            "title": "Foco guiado",
            "description": "Use os filtros avançados para criar o treino perfeito.",
            "meta": "Personalize categorias, dificuldade e número de questões.",
            "icon": "insights",
            "dom_id": "hub-smart-drill-btn",
            "extra_css_class": "challenge-card--accent",
            "is_enabled": True,
        },
    )
    ChallengeHubActionCard.objects.update_or_create(
        settings=challenge_settings,
        key="timed_quiz",
        defaults={
            "title": "Simulado cronometrado",
            "description": "Bloco intenso de 40 questões para testar seu ritmo.",
            "meta": "Ideal para treinar provas completas.",
            "icon": "timer",
            "dom_id": "hub-timed-quiz-btn",
            "extra_css_class": "",
            "is_enabled": True,
        },
    )
    ChallengeHubActionCard.objects.update_or_create(
        settings=challenge_settings,
        key="favorite_review",
        defaults={
            "title": "Revisão de favoritos",
            "description": "Revise rapidamente as questões marcadas com estrela.",
            "meta": "Perfeito para revisões direcionadas.",
            "icon": "star",
            "dom_id": "hub-favorite-review-btn",
            "extra_css_class": "",
            "is_enabled": True,
        },
    )
    ChallengeHubActionCard.objects.update_or_create(
        settings=challenge_settings,
        key="repeat_last",
        defaults={
            "title": "Repetir último desafio",
            "description": "Refaça instantaneamente o último conjunto de questões.",
            "meta": "Mantém filtros e sequência anteriores.",
            "icon": "refresh",
            "dom_id": "hub-repeat-last-btn",
            "extra_css_class": "challenge-card--ghost",
            "is_enabled": True,
        },
    )

    ChallengeHubResumeCardSettings.objects.get_or_create(
        settings=challenge_settings,
        defaults={
            "title": "Retomar sessão",
            "description_template": "Você tem uma sessão em andamento de <strong>{question_count}</strong> questões.",
            "icon": "autorenew",
            "discard_label": "Descartar",
            "continue_label": "Continuar",
        },
    )

    ChallengeHubPredefinedSection.objects.get_or_create(
        settings=challenge_settings,
        defaults={
            "title": "Listas especiais",
            "subtitle": "Explore quizzes prontos com curadoria da equipe MedQuiz.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0019_challengehubsettings_homepagesettings_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_content, migrations.RunPython.noop),
    ]
