# Generated by Django 5.2.7 on 2025-10-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0020_populate_home_challenge_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeHubPlaceholderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filters_title",
                    models.CharField(default="Ajuste seus filtros", max_length=200),
                ),
                (
                    "filters_body",
                    models.CharField(
                        default="O painel lateral está aberto. Escolha categorias e dificuldade para liberar novos desafios.",
                        max_length=300,
                    ),
                ),
                (
                    "filters_supporting",
                    models.CharField(
                        blank=True,
                        default='Após aplicar os filtros, clique em "Aplicar" para atualizar o hub.',
                        max_length=300,
                    ),
                ),
                (
                    "filters_cta_label",
                    models.CharField(
                        default="Voltar para Modos de Jogo", max_length=150
                    ),
                ),
                (
                    "filters_cta_icon",
                    models.CharField(default="arrow_back", max_length=80),
                ),
                (
                    "filters_cta_css_class",
                    models.CharField(
                        default="button button--secondary button--small", max_length=200
                    ),
                ),
                (
                    "filters_cta_dom_id",
                    models.CharField(
                        default="close-filters-and-show-hub-btn",
                        help_text="ID aplicado ao botão que fecha os filtros.",
                        max_length=120,
                    ),
                ),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placeholders",
                        to="quiz.challengehubsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagens auxiliares do Challenge Hub",
            },
        ),
        migrations.CreateModel(
            name="HomeAchievementCardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(default="emoji_events", max_length=80)),
                (
                    "eyebrow",
                    models.CharField(default="Próxima conquista", max_length=150),
                ),
                (
                    "fallback_title",
                    models.CharField(
                        default="Acompanhe suas conquistas", max_length=200
                    ),
                ),
                (
                    "fallback_description",
                    models.CharField(
                        blank=True,
                        default="Complete desafios para desbloquear medalhas e acompanhar o progresso.",
                        max_length=300,
                    ),
                ),
                ("progress_label", models.CharField(default="Status", max_length=120)),
                (
                    "progress_placeholder",
                    models.CharField(default="0%", max_length=120),
                ),
                (
                    "show_when_empty",
                    models.BooleanField(
                        default=True,
                        help_text="Exibe o card mesmo sem conquista pendente.",
                    ),
                ),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_card",
                        to="quiz.homepagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card de conquista",
            },
        ),
        migrations.CreateModel(
            name="HomeActiveChallengeCardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(default="flag", max_length=80)),
                (
                    "eyebrow",
                    models.CharField(default="Desafio em andamento", max_length=150),
                ),
                (
                    "fallback_title",
                    models.CharField(default="Nenhum desafio ativo", max_length=200),
                ),
                (
                    "fallback_description",
                    models.CharField(
                        blank=True,
                        default="Personalize o hub para iniciar um novo desafio em segundos.",
                        max_length=300,
                    ),
                ),
                (
                    "badge_label_template",
                    models.CharField(
                        blank=True,
                        default="Termina em {time_remaining}",
                        help_text="Use {time_remaining} para inserir a contagem restante.",
                        max_length=160,
                    ),
                ),
                (
                    "progress_label",
                    models.CharField(default="Progresso", max_length=120),
                ),
                (
                    "progress_placeholder",
                    models.CharField(default="0%", max_length=120),
                ),
                (
                    "reward_label_template",
                    models.CharField(
                        blank=True,
                        default="Recompensa: {reward}",
                        help_text="Use {reward} para exibir a recompensa.",
                        max_length=160,
                    ),
                ),
                (
                    "reward_placeholder",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "show_when_empty",
                    models.BooleanField(
                        default=True,
                        help_text="Mantém o card visível para incentivar a criação de desafios.",
                    ),
                ),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_challenge_card",
                        to="quiz.homepagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card de desafio ativo",
            },
        ),
        migrations.CreateModel(
            name="HomeProgressSectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Resumo rápido do seu estudo",
                        help_text="Título exibido quando o aluno está autenticado.",
                        max_length=200,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="Entre direto nos modos que mantêm sua evolução em alta.",
                        help_text="Descrição auxiliar da seção de progresso.",
                        max_length=250,
                    ),
                ),
                (
                    "show_when_empty",
                    models.BooleanField(
                        default=False,
                        help_text="Mantém a seção visível mesmo quando nenhum card tem dados.",
                    ),
                ),
                (
                    "empty_state_title",
                    models.CharField(
                        default="Comece um treino para ver estatísticas aqui",
                        max_length=200,
                    ),
                ),
                (
                    "empty_state_description",
                    models.CharField(
                        blank=True,
                        default="Assim que você concluir uma sessão ou desafio, os destaques aparecem automaticamente.",
                        max_length=300,
                    ),
                ),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_section",
                        to="quiz.homepagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção de progresso da home",
            },
        ),
        migrations.CreateModel(
            name="HomeRecentSessionCardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(default="history", max_length=80)),
                ("eyebrow", models.CharField(default="Última sessão", max_length=150)),
                (
                    "fallback_title",
                    models.CharField(
                        default="Sessão mais recente",
                        help_text="Título usado quando não há sessão registrada.",
                        max_length=200,
                    ),
                ),
                (
                    "fallback_description",
                    models.CharField(
                        blank=True,
                        default="Inicie um quiz para destravar análises detalhadas da sua sessão.",
                        max_length=250,
                    ),
                ),
                (
                    "badge_label_template",
                    models.CharField(
                        blank=True,
                        default="{date_display}",
                        help_text="Use {date_display} para inserir a data da sessão.",
                        max_length=160,
                    ),
                ),
                ("stat_mode_label", models.CharField(default="Modo", max_length=80)),
                (
                    "stat_method_label",
                    models.CharField(default="Método", max_length=80),
                ),
                (
                    "stat_questions_label",
                    models.CharField(default="Questões", max_length=80),
                ),
                (
                    "stat_accuracy_label",
                    models.CharField(default="Precisão", max_length=80),
                ),
                (
                    "stat_duration_label",
                    models.CharField(default="Duração", max_length=80),
                ),
                ("stat_mode_placeholder", models.CharField(default="—", max_length=80)),
                (
                    "stat_method_placeholder",
                    models.CharField(default="—", max_length=80),
                ),
                (
                    "stat_questions_placeholder",
                    models.CharField(default="0", max_length=80),
                ),
                (
                    "stat_accuracy_placeholder",
                    models.CharField(default="0%", max_length=80),
                ),
                (
                    "stat_duration_placeholder",
                    models.CharField(default="0 min", max_length=80),
                ),
                (
                    "cta_label",
                    models.CharField(default="Retomar treino", max_length=120),
                ),
                ("cta_url", models.CharField(default="/questions/", max_length=255)),
                (
                    "cta_icon",
                    models.CharField(blank=True, default="play_arrow", max_length=80),
                ),
                (
                    "cta_css_class",
                    models.CharField(default="button button--text", max_length=200),
                ),
                (
                    "show_when_empty",
                    models.BooleanField(
                        default=False,
                        help_text="Mantém o card visível mesmo sem sessão recente.",
                    ),
                ),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_session_card",
                        to="quiz.homepagesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card de sessão recente",
            },
        ),
    ]
