# Generated by Django 5.2.7 on 2025-10-08 14:00

from django.db import migrations


def create_card_settings(apps, schema_editor):
    HomePageSettings = apps.get_model('quiz', 'HomePageSettings')
    HomeProgressSectionSettings = apps.get_model('quiz', 'HomeProgressSectionSettings')
    HomeRecentSessionCardSettings = apps.get_model('quiz', 'HomeRecentSessionCardSettings')
    HomeActiveChallengeCardSettings = apps.get_model('quiz', 'HomeActiveChallengeCardSettings')
    HomeAchievementCardSettings = apps.get_model('quiz', 'HomeAchievementCardSettings')
    ChallengeHubSettings = apps.get_model('quiz', 'ChallengeHubSettings')
    ChallengeHubPlaceholderSettings = apps.get_model('quiz', 'ChallengeHubPlaceholderSettings')

    home_settings, _ = HomePageSettings.objects.get_or_create(pk=1)
    HomeProgressSectionSettings.objects.get_or_create(settings=home_settings)
    HomeRecentSessionCardSettings.objects.get_or_create(settings=home_settings)
    HomeActiveChallengeCardSettings.objects.get_or_create(settings=home_settings)
    HomeAchievementCardSettings.objects.get_or_create(settings=home_settings)

    challenge_settings, _ = ChallengeHubSettings.objects.get_or_create(pk=1)
    ChallengeHubPlaceholderSettings.objects.get_or_create(settings=challenge_settings)


def noop(apps, schema_editor):
    """No-op reverse migration."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0021_challengehubplaceholdersettings_and_more"),
    ]

    operations = [
        migrations.RunPython(create_card_settings, noop),
    ]
