# Generated by Django 5.2.1 on 2025-10-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_merge_20251012_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='slug',
            field=models.SlugField(
                blank=True,
                null=True,
                help_text='Identificador amigável usado nas URLs públicas da pergunta.',
                max_length=220,
                verbose_name='Slug legível',
            ),
        ),
        migrations.AddField(
            model_name='quizdefinicao',
            name='slug',
            field=models.SlugField(
                blank=True,
                null=True,
                help_text='Identificador amigável usado nas URLs públicas do desafio/quiz.',
                max_length=180,
                verbose_name='Slug legível',
            ),
        ),
    ]
