# Generated by Django 5.2.1 on 2025-10-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em análise'), ('resolved', 'Resolvido'), ('archived', 'Arquivado')], default='open', max_length=24, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='tipo_contato',
            field=models.CharField(choices=[('general', 'Dúvida ou orientação'), ('technical_issue', 'Problema técnico'), ('content_error', 'Erro em conteúdo'), ('improvement', 'Sugestão de melhoria')], default='general', help_text='Ajuda a classificar rapidamente o motivo principal do contato.', max_length=32, verbose_name='Tipo de contato'),
        ),
    ]
