# Generated by Django 5.2.1 on 2025-10-13 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_supportrequest_atualizado_em_supportrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do modo')),
                ('slug', models.SlugField(help_text='Identificador utilizado em URLs internas e scripts.', max_length=180, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('meta', models.CharField(blank=True, help_text='Texto exibido no rodapé do card (ex.: número de questões ou dica rápida).', max_length=160, verbose_name='Etiqueta auxiliar')),
                ('icon', models.CharField(default='sports_esports', help_text="Nome do ícone Material Symbols (ex.: 'flag', 'auto_stories').", max_length=80, verbose_name='Ícone')),
                ('accent_color', models.CharField(blank=True, help_text='Opcional: cor CSS (ex.: #4caf50) aplicada a detalhes visuais do card.', max_length=40, verbose_name='Cor de destaque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_definition', models.ForeignKey(help_text='Definição que será executada ao iniciar este modo.', on_delete=django.db.models.deletion.CASCADE, related_name='training_modes', to='quiz.quizdefinicao', verbose_name='Quiz associado')),
            ],
            options={
                'verbose_name': 'Modo de Treino',
                'verbose_name_plural': 'Modos de Treino',
                'ordering': ('order', 'name'),
            },
        ),
    ]
