# Generated by Django 5.2.1 on 2025-10-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_trainingmode'),
    ]

    @staticmethod
    def _create_training_modes(apps, schema_editor):
        QuizDefinicao = apps.get_model('quiz', 'QuizDefinicao')
        TrainingMode = apps.get_model('quiz', 'TrainingMode')

        definition_specs = [
            {
                'slug': 'revisao-inteligente',
                'defaults': {
                    'nome_quiz': 'Revisão inteligente',
                    'descricao': 'Combina os seus favoritos com um algoritmo de priorização espaçada para revisar o que mais importa.',
                    'ativo': True,
                    'generation_type': 'favorites',
                    'generation_config': {
                        'limit': 12,
                        'sort': 'recent',
                        'include_inactive': False,
                    },
                    'study_method_override': 'spaced_repetition',
                },
            },
            {
                'slug': 'blitz-diagnostica',
                'defaults': {
                    'nome_quiz': 'Blitz diagnóstica',
                    'descricao': 'Seleção rápida de 20 questões variadas para mapear seus pontos fortes e fracos.',
                    'ativo': True,
                    'generation_type': 'filters',
                    'generation_config': {
                        'limit': 20,
                        'shuffle': True,
                    },
                    'study_method_override': 'random',
                },
            },
        ]

        definitions_by_slug = {}
        for spec in definition_specs:
            defaults = spec['defaults'].copy()
            defaults['slug'] = spec['slug']
            quiz_def, _ = QuizDefinicao.objects.update_or_create(
                slug=spec['slug'],
                defaults=defaults,
            )
            definitions_by_slug[spec['slug']] = quiz_def

        training_mode_specs = [
            {
                'slug': 'modo-revisao-inteligente',
                'name': 'Revisão inteligente',
                'description': 'Reforce seus favoritos com revisão espaçada automática e feedback personalizado.',
                'meta': 'Favoritos + revisão SM-2',
                'icon': 'auto_fix',
                'accent_color': '#5D8DEE',
                'order': 10,
                'quiz_slug': 'revisao-inteligente',
            },
            {
                'slug': 'modo-blitz-diagnostica',
                'name': 'Blitz diagnóstica',
                'description': 'Rodada dinâmica de questões variadas para testar seu raciocínio clínico em poucos minutos.',
                'meta': '20 questões • mistura adaptativa',
                'icon': 'bolt',
                'accent_color': '#F28A2B',
                'order': 20,
                'quiz_slug': 'blitz-diagnostica',
            },
        ]

        for spec in training_mode_specs:
            quiz_def = definitions_by_slug.get(spec['quiz_slug'])
            if not quiz_def:
                continue

            TrainingMode.objects.update_or_create(
                slug=spec['slug'],
                defaults={
                    'name': spec['name'],
                    'description': spec['description'],
                    'meta': spec['meta'],
                    'icon': spec['icon'],
                    'accent_color': spec['accent_color'],
                    'order': spec['order'],
                    'is_active': True,
                    'quiz_definition': quiz_def,
                },
            )

    @staticmethod
    def _delete_training_modes(apps, schema_editor):
        TrainingMode = apps.get_model('quiz', 'TrainingMode')
        QuizDefinicao = apps.get_model('quiz', 'QuizDefinicao')

        mode_slugs = ['modo-revisao-inteligente', 'modo-blitz-diagnostica']
        definition_slugs = ['revisao-inteligente', 'blitz-diagnostica']

        TrainingMode.objects.filter(slug__in=mode_slugs).delete()

        for slug in definition_slugs:
            try:
                quiz_def = QuizDefinicao.objects.get(slug=slug)
            except QuizDefinicao.DoesNotExist:
                continue

            has_modes = quiz_def.training_modes.exists()
            has_action_cards = quiz_def.linked_action_cards.exists()
            if not has_modes and not has_action_cards:
                quiz_def.delete()

    operations = [
        migrations.RunPython(
            code=_create_training_modes,
            reverse_code=_delete_training_modes,
        ),
    ]
