"""
Django settings for medquiz_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-66aois=68ij*lt^k%liy0v@w-omj&z+0-1$w=13n-akp*+9n*z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.ngrok-free.app',  # Mantém isso para cobrir o acesso geral
    '7ea944ff518d.ngrok-free.app', # Adicione o host específico também
]

CSRF_TRUSTED_ORIGINS = [
    "https://7ea944ff518d.ngrok-free.app"
    # Se o ngrok gerar uma nova URL na próxima vez, você precisará atualizá-la aqui também
    # ou, se o ngrok sempre usar o mesmo domínio base (ex: .ngrok-free.app) e você confia nele,
    # algumas versões mais recentes do Django podem permitir wildcards aqui com cuidado,
    # mas para ngrok, é mais seguro ser explícito com a URL HTTPS completa.
    # Para maior flexibilidade com subdomínios aleatórios, você pode tentar:
    # 'https://*.ngrok-free.app' (verifique a documentação do Django para a sua versão
    # sobre o suporte a wildcards em CSRF_TRUSTED_ORIGINS).
    # No entanto, a URL HTTPS completa é a mais segura.
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'quiz.apps.QuizConfig',
    # 'quiz',  # Adicione esta linha para registrar o aplicativo quiz
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medquiz_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'quiz.context_processors.avatar_context',
                'quiz.context_processors.system_message_broadcasts',
            ],
        },
    },
]

WSGI_APPLICATION = 'medquiz_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-BR'  # ALTERADO AQUI

TIME_ZONE = 'America/Sao_Paulo' # ALTERADO AQUI (ou o fuso horário de sua preferência no Brasil)

USE_I18N = True  # MANTENHA COMO TRUE

USE_L10N = True  # ADICIONE OU MANTENHA COMO TRUE (para formatação localizada de números e datas)

USE_TZ = True    # MANTENHA COMO TRUE

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets') # Onde seus arquivos CSS/JS/data estão atualmente
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'  # Ou '/accounts/login/' se você estiver usando as URLs padrão do Django Auth diretamente
LOGIN_REDIRECT_URL = 'quiz:home' # Para onde ir após o login bem-sucedido
LOGOUT_REDIRECT_URL = 'quiz:home' # Para onde ir após o logout